version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - 4000:4000
    volumes:
      - D:\docker_explore\ninja\docker-crash-course\api:/app
      - D:\docker_explore\ninja\docker-crash-course\api\node_modules:/app/node_modules

  react-app:
    build: ./react-app
    container_name: react_container
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
